"""
Configuration settings for the Voice Agent Simulator application

LEARNING NOTES:
===============
This configuration file demonstrates best practices for managing application settings:

1. **Environment Variables**: All sensitive data (API keys, endpoints) stored as env vars
2. **Defaults**: Sensible defaults provided for development environment
3. **Separation**: Azure, Flask, and Agent configs clearly separated
4. **Validation**: Config validation ensures required settings are present
5. **Security**: Connection strings and API keys never hardcoded in code

KEY CONCEPTS:
- Use python-dotenv to load from .env file in development
- In production (Azure Container Apps), environment variables set in Bicep
- DefaultAzureCredential allows authentication without API keys (recommended)
"""
import os
from dotenv import load_dotenv

# Load environment variables from .env file (development only)
load_dotenv()

class Config:
    """Application configuration loaded from environment variables"""
    
    # ============================================================================
    # Flask Configuration
    # ============================================================================
    # SECRET_KEY: Used by Flask for session encryption
    # IMPORTANT: Change this in production! Use: python -c "import secrets; print(secrets.token_hex(32))"
    SECRET_KEY = os.getenv('FLASK_SECRET_KEY', 'dev-secret-key-change-in-production')
    
    # ENV: Controls debug mode and other environment-specific behavior
    ENV = os.getenv('FLASK_ENV', 'development')
    DEBUG = ENV == 'development'
    
    # PORT: Default 5000 for Flask, but can be overridden
    PORT = int(os.getenv('FLASK_PORT', 5000))
    
    # ============================================================================
    # Azure AI Foundry Configuration
    # ============================================================================
    # ENDPOINT: Your Azure AI Foundry project endpoint (REQUIRED)
    # Format: https://<your-project>.cognitiveservices.azure.com/
    AZURE_AI_FOUNDRY_ENDPOINT = os.getenv('AZURE_AI_FOUNDRY_ENDPOINT')
    
    # API_KEY: Optional - if not provided, uses Azure CLI auth (DefaultAzureCredential)
    # In production with managed identity, this should be empty
    AZURE_AI_FOUNDRY_API_KEY = os.getenv('AZURE_AI_FOUNDRY_API_KEY')
    
    # MODEL_NAME: The deployment name of your GPT model
    # This is the name you chose when deploying the model in AI Foundry
    AZURE_AI_MODEL_NAME = os.getenv('AZURE_AI_MODEL_NAME', 'gpt-4o')
    
    # DEPLOYMENT_NAME: Alias for model name (some SDKs use different terminology)
    AZURE_OPENAI_DEPLOYMENT_NAME = os.getenv('AZURE_OPENAI_DEPLOYMENT_NAME')
    
    # ============================================================================
    # Azure Storage Configuration
    # ============================================================================
    # STORAGE_ACCOUNT_NAME: Your Azure Storage account for conversation scores
    # NOTE: No default here - will be generated by Bicep during deployment
    # The value 'voiceagent3799' was just one deployment's generated name
    AZURE_STORAGE_ACCOUNT_NAME = os.getenv('AZURE_STORAGE_ACCOUNT_NAME')
    
    # Construct endpoints from account name (Azure Storage standard URLs)
    AZURE_STORAGE_BLOB_ENDPOINT = f"https://{AZURE_STORAGE_ACCOUNT_NAME}.blob.core.windows.net" if AZURE_STORAGE_ACCOUNT_NAME else None
    AZURE_STORAGE_TABLE_ENDPOINT = f"https://{AZURE_STORAGE_ACCOUNT_NAME}.table.core.windows.net" if AZURE_STORAGE_ACCOUNT_NAME else None
    
    # CONNECTION_STRING: Only needed for local development
    # In production (Azure), use managed identity instead
    AZURE_STORAGE_CONNECTION_STRING = os.getenv('AZURE_STORAGE_CONNECTION_STRING')
    
    # ============================================================================
    # Agent Configuration
    # ============================================================================
    # Customize your agent's identity and behavior
    AGENT_NAME = os.getenv('AGENT_NAME', 'CORA - Customer Service Simulator')
    AGENT_DESCRIPTION = os.getenv('AGENT_DESCRIPTION', 
                                   'AI voice agent for training customer service representatives')
    
    # ============================================================================
    # System Prompt - The Agent's Core Instructions
    # ============================================================================
    # This prompt defines the agent's personality, role, and behavior
    # Key learning: System prompts should be:
    #   - Clear and specific about the agent's role
    #   - Include do's and don'ts
    #   - Set expectations for tone and style
    AGENT_SYSTEM_PROMPT = """You are Cora, a digital customer simulator designed to help train customer service agents.
    
Your role is to:
1. Act as a customer with a specific need or problem based on the scenario
2. Engage naturally with the human customer service agent who is helping you
3. Provide information when asked and respond to the agent's questions
4. React authentically based on how well the agent is handling your situation
5. Stay in character as a customer throughout the conversation

Important:
- YOU are Cora, the customer seeking help
- The human you're talking to is a customer service agent in training trying to help YOU
- Start conversations by presenting your issue or question as a customer would
- Do NOT say "How can I help you today?" - that's what the AGENT says to YOU
- Respond naturally to the agent's questions and solutions
- Express satisfaction when helped well, or frustration if not helped effectively
- Keep responses concise and realistic (2-4 sentences typically)
"""
    
    @staticmethod
    def validate_config():
        """
        Validate that required configuration is present
        
        LEARNING NOTE: Always validate config at startup to fail fast
        Better to error immediately than to fail mid-request
        """
        # Only endpoint is strictly required (API key is optional with Azure CLI auth)
        if not os.getenv('AZURE_AI_FOUNDRY_ENDPOINT'):
            raise ValueError(
                "Missing required environment variable: AZURE_AI_FOUNDRY_ENDPOINT\n"
                "Please set this in your .env file or Azure Container App environment"
            )
        
        # Warn if no API key (will use Azure CLI credentials or managed identity)
        if not os.getenv('AZURE_AI_FOUNDRY_API_KEY'):
            print("⚠️  No API key provided. Using DefaultAzureCredential")
            print("   Local development: Make sure you're logged in with 'az login'")
            print("   Production: Ensure managed identity has Cognitive Services User role")
